server:
  port: 8501

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.189.149:3306/xht_admin?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yzd2021$$
  data:
    redis:
      host: 123.60.189.149
      port: 6379
      password: yzd2021$$


mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml
  global-config:
    db-config:
      id-type: auto
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xht.manager
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 自定义jwt key
jwt:
  token: token #JWT存储的请求头
  secret: xhtSecret #JWT加解密使用的密钥
  expiration: 604800000 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头